version: '3.9'

services:
  # DATABASE
  mysql: 
    container_name: mysql
    image: mysql:8.0
    tty: true
    working_dir: /var/lib/mysql
    volumes:
      - ./dbData_mysql:/var/lib/mysql 
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: library_db
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - 3306:3306     
    networks:
      - backend                 
  # PHP My Admin
  phpmyadmin: 
    container_name: phpmyadmin
    depends_on: 
      - mysql
    image: phpmyadmin/phpmyadmin
    restart: 'always'
    environment: 
      MYSQL_ROOT_PASSWORD: root
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITARY: 1
    ports: 
      - 8080:80
    networks:
      - backend        
  # Node
  app:
    container_name: app
    depends_on:
      - mysql
    build:
      context: ./    
      dockerfile: Dockerfile
    tty: true
    restart: 'always'
    working_dir: /usr/src/library_api
    volumes:
      - ./:/usr/src/library_api
    command: npm run docker-boot-up
    ports:
      - 5000:5000          
    networks:
      - backend
# Network
networks:
  backend:
    driver: bridge    
# Volume
volumes:
  postgres:
  pgadmin:



# docker-compose run -p 6000:5000 --rm app npm run docker-bootstrap-fresh